
cc_library(
    name = "bembo",
    srcs = ["doc.cc"],
    hdrs = ["doc.h"],
    copts = [
        "-std=c++20",
        "-fno-rtti",
        "-fno-exceptions",
        "-Wall",
        "-Werror",
        "-Wmissing-field-initializers",
        "-Wimplicit-fallthrough",
    ],
    visibility = ["//visibility:public"],
)
