
cc_library(
    name = "bembo",
    srcs = ["doc.cc"],
    hdrs = ["doc.h"],
    copts = ["-std=c++17", "-Wall", "-Werror", "-Wmissing-field-initializers"],
    visibility = ["//visibility:public"],
)
