#!/usr/bin/env bash

set -euo pipefail

root="$(dirname "${BASH_SOURCE[0]}")/.."

tmpfile="$(mktemp)"

cat <<EOF > "$tmpfile"
# Automatically generated by //scripts/build_compdb.sh
TARGETS = [
EOF

bazelisk query 'kind("cc_(binary|library)", //...)' | \
  sort | \
  while read -r target; do
    echo "    \"${target}\"," >> "$tmpfile"
  done

echo "]" >> "$tmpfile"

mv "$tmpfile" "$root/rules/compdb_targets.bzl"

outfile="$(bazelisk info bazel-bin)/compile_commands.json"

bazelisk build //:compdb

cp "$outfile" "$root/compile_commands.json"
chmod 0644 "$root/compile_commands.json"
